### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Alecsarky** [Zetsyog/Grab#1]
Bonjour ! Quelle est la permission pour craft et utiliser le grappin ?
Et aussi existe-t-il une commande pour se le give ?

**Comment by Zetsyog** [comment]
Désolé c'est un vieux plugin que j'ai fait rapidement (il est plus maintenu depuis plus d'un an) Du coup pas de permission et pas de commande non plus désolé.

**Comment by Alecsarky** [comment]
Dommage car c'est le seul plugin avec un grappin qui marche parfaitement . Du coup tu as fais quoi d'autre comme plugins ?

**Comment by Zetsyog** [comment]
Rien j'ai arrêté désolé.

**Comment by Alecsarky** [comment]
Ok , Au revoir
